#服务端口
server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  datasource:
    url: jdbc:mysql://192.168.101.118:3306/cudemo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: liugf
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000



jwt:
  secret: saasasasas